using Microsoft.CodeAnalysis;
using Portcullis.Rules;

namespace Portcullis.Engine.Tests.Rules;

/// <summary>
/// PORTCULLIS_MIG_SYNC_OVER_ASYNC. Each blocking shape on each task type fires once; the two
/// shapes the rule can prove complete (a ContinueWith antecedent, a completion-guarded
/// branch) do not, and neither does anything that only looks like a task —
/// <c>SemaphoreSlim.Wait()</c>, a team's <c>Result</c> property, a non-task awaiter.
/// </summary>
public class SyncOverAsyncAnalyzerTests
{
    private static readonly string RuleId = SyncOverAsyncAnalyzer.SyncOverAsyncRule.Id;

    private static async Task<List<Diagnostic>> RunAsync(string source, string path = "src/Shop/Orders.cs")
    {
        var diagnostics = await AnalyzerTestHelper.GetDiagnosticsAsync(new SyncOverAsyncAnalyzer(), (path, source));
        // Concurrent execution reports in no fixed order; tests read them in source order.
        return diagnostics.Where(d => d.Id == RuleId).OrderBy(d => d.Location.SourceSpan.Start).ToList();
    }

    // Wraps statements in a method that has a Task, a Task<int>, a ValueTask and a
    // ValueTask<int> in scope as parameters, so every case below binds for real.
    private static Task<List<Diagnostic>> RunStatementsAsync(string statements) => RunAsync($$"""
        using System;
        using System.Threading;
        using System.Threading.Tasks;

        namespace Shop;

        public class Orders
        {
            private readonly Task<int> _pending = Task.FromResult(0);

            private Task<int> Pending { get; } = Task.FromResult(0);

            public int Run(Task task, Task<int> count, ValueTask done, ValueTask<int> total, Task<int> other, bool flag, Orders peer)
            {
                int value = 0;
                {{statements}}
                return value;
            }
        }
        """);

    private static string Located(Diagnostic diagnostic) =>
        diagnostic.Location.SourceTree!.GetText().ToString(diagnostic.Location.SourceSpan);

    // --- what fires ---

    [Fact]
    public async Task FiresOnResultOfATaskOfT()
    {
        var hits = await RunStatementsAsync("value = count.Result;");

        var hit = Assert.Single(hits);
        Assert.Equal("count.Result", Located(hit));
        Assert.Contains("Task<TResult>.Result", hit.GetMessage());
        Assert.Equal(DiagnosticSeverity.Warning, hit.Severity);
    }

    [Fact]
    public async Task FiresOnResultOfAValueTaskOfT()
    {
        var hits = await RunStatementsAsync("value = total.Result;");

        Assert.Contains("(ValueTask<TResult>.Result)", Assert.Single(hits).GetMessage());
    }

    [Fact]
    public async Task ReportsTheFullMessage_AndTellsPropertiesFromMethods()
    {
        var result = Assert.Single(await RunStatementsAsync("value = count.Result;"));
        var wait = Assert.Single(await RunStatementsAsync("task.Wait();"));

        Assert.Equal(
            "'count.Result' blocks the calling thread until the task completes (Task<TResult>.Result). Under a " +
            "synchronization context that deadlocks; on ASP.NET Core it holds a thread-pool thread for the " +
            "whole wait. Make the caller async and await the task instead.",
            result.GetMessage());
        Assert.Contains("(Task.Wait())", wait.GetMessage());
    }

    [Fact]
    public async Task DoesNotFireInGeneratedCode()
    {
        var hits = await RunAsync("""
            // <auto-generated />
            using System.Threading.Tasks;

            namespace Shop;

            public class Designer
            {
                public int Count(Task<int> pending) => pending.Result;
            }
            """);

        Assert.Empty(hits);
    }

    [Fact]
    public async Task FiresInsideAContinueWithThatIsNotATasksOwn()
    {
        // Only Task/Task<T>.ContinueWith guarantees a finished antecedent; a pipeline's own
        // ContinueWith guarantees nothing.
        var hits = await RunAsync("""
            using System;
            using System.Threading.Tasks;

            namespace Shop;

            public sealed class Pipeline
            {
                public Pipeline ContinueWith(Func<Task<int>, int> step) => this;
            }

            public class Orders
            {
                public Pipeline Run(Pipeline pipeline) => pipeline.ContinueWith(pending => pending.Result);
            }
            """);

        Assert.Equal("pending.Result", Located(Assert.Single(hits)));
    }

    [Theory]
    [InlineData("task.Wait();")]
    [InlineData("task.Wait(100);")]
    [InlineData("task.Wait(TimeSpan.FromSeconds(1));")]
    [InlineData("task.Wait(CancellationToken.None);")]
    [InlineData("count.Wait();")]
    [InlineData("Task.WaitAll(task, count);")]
    [InlineData("Task.WaitAny(task, count);")]
    public async Task FiresOnEveryWaitShape(string statement)
    {
        var hits = await RunStatementsAsync(statement);

        Assert.Equal(statement.TrimEnd(';'), Located(Assert.Single(hits)));
    }

    [Theory]
    [InlineData("task.GetAwaiter().GetResult();", "TaskAwaiter.GetResult()")]
    [InlineData("value = count.GetAwaiter().GetResult();", "TaskAwaiter<TResult>.GetResult()")]
    [InlineData("done.GetAwaiter().GetResult();", "ValueTaskAwaiter.GetResult()")]
    [InlineData("value = total.GetAwaiter().GetResult();", "ValueTaskAwaiter<TResult>.GetResult()")]
    [InlineData("task.ConfigureAwait(false).GetAwaiter().GetResult();", "ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()")]
    [InlineData("value = count.ConfigureAwait(false).GetAwaiter().GetResult();", "ConfiguredTaskAwaitable<TResult>.ConfiguredTaskAwaiter.GetResult()")]
    [InlineData("done.ConfigureAwait(false).GetAwaiter().GetResult();", "ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter.GetResult()")]
    [InlineData("value = total.ConfigureAwait(false).GetAwaiter().GetResult();", "ConfiguredValueTaskAwaitable<TResult>.ConfiguredValueTaskAwaiter.GetResult()")]
    public async Task FiresOnGetResultOfEveryTaskAwaiter(string statement, string shape)
    {
        var hits = await RunStatementsAsync(statement);

        Assert.Contains(shape, Assert.Single(hits).GetMessage());
    }

    [Fact]
    public async Task FiresOnAnAwaiterHeldInAVariable()
    {
        var hits = await RunStatementsAsync("var awaiter = count.GetAwaiter(); value = awaiter.GetResult();");

        Assert.Equal("awaiter.GetResult()", Located(Assert.Single(hits)));
    }

    [Fact]
    public async Task FiresOnATaskReturnedByAFrameworkApi()
    {
        // HttpClient lives in System.Net.Http, not corelib: this binds only because the scan
        // references the runtime's framework assemblies.
        var hits = await RunAsync("""
            using System.Net.Http;

            namespace Shop;

            public class Rates
            {
                public string Fetch(HttpClient client) => client.GetStringAsync("https://example.test/rates").Result;
            }
            """);

        Assert.Equal("client.GetStringAsync(\"https://example.test/rates\").Result", Located(Assert.Single(hits)));
    }

    [Fact]
    public async Task FiresOnAContinuationThatBlocksOnADifferentTask()
    {
        var hits = await RunStatementsAsync("count.ContinueWith(previous => other.Result);");

        Assert.Equal("other.Result", Located(Assert.Single(hits)));
    }

    [Theory]
    [InlineData("if (!count.IsCompleted) { value = count.Result; }")]
    [InlineData("if (count.IsCompleted || flag) { value = count.Result; }")]
    [InlineData("if (count.IsCompleted) { } else { value = count.Result; }")]
    [InlineData("if (other.IsCompleted) { value = count.Result; }")]
    [InlineData("value = !count.IsCompleted ? count.Result : 0;")]
    public async Task FiresWhenTheConditionDoesNotProveThisTaskComplete(string statements)
    {
        var hits = await RunStatementsAsync(statements);

        Assert.Equal("count.Result", Located(Assert.Single(hits)));
    }

    [Theory]
    [InlineData("if (peer._pending.IsCompleted) return _pending.Result;", "_pending.Result")]
    [InlineData("if (peer.Pending.IsCompleted) return Pending.Result;", "Pending.Result")]
    public async Task FiresWhenTheGuardChecksTheSameMemberOnAnotherObject(string statements, string expected)
    {
        var hits = await RunStatementsAsync(statements);

        Assert.Equal(expected, Located(Assert.Single(hits)));
    }

    // --- what does not ---

    [Fact]
    public async Task DoesNotFireOnAwait()
    {
        var hits = await RunAsync("""
            using System.Threading.Tasks;

            namespace Shop;

            public class Orders
            {
                public async Task<int> Count(Task<int> pending) => await pending;
            }
            """);

        Assert.Empty(hits);
    }

    [Theory]
    [InlineData("value = count.ContinueWith(previous => previous.Result).Result;", "count.ContinueWith(previous => previous.Result).Result")]
    [InlineData("count.ContinueWith(previous => previous.GetAwaiter().GetResult());", null)]
    [InlineData("count.ContinueWith((previous, state) => previous.Result, null);", null)]
    [InlineData("task.ContinueWith(previous => previous.Wait());", null)]
    [InlineData("count.ContinueWith(previous => previous.ConfigureAwait(false).GetAwaiter().GetResult());", null)]
    public async Task DoesNotFireOnTheAntecedentInsideAContinuation(string statements, string? outerBlockingCall)
    {
        var hits = await RunStatementsAsync(statements);

        // Only the outer `.Result` on the continuation itself (first case) is a real wait.
        Assert.Equal(outerBlockingCall is null ? [] : new[] { outerBlockingCall }, hits.Select(Located).ToArray());
    }

    [Theory]
    [InlineData("if (count.IsCompleted) { value = count.Result; }")]
    [InlineData("if (count.IsCompletedSuccessfully) return count.Result;")]
    [InlineData("value = count.IsCompletedSuccessfully ? count.Result : 0;")]
    [InlineData("if (flag && count.IsCompleted) { value = count.GetAwaiter().GetResult(); }")]
    [InlineData("if (total.IsCompletedSuccessfully) return total.Result;")]
    [InlineData("if (_pending.IsCompleted) return _pending.Result;")]
    [InlineData("if (task.IsCompleted) { task.Wait(); }")]
    [InlineData("if (Pending.IsCompleted) return Pending.Result;")]
    [InlineData("if (count.IsCompleted) { value = count.ConfigureAwait(false).GetAwaiter().GetResult(); }")]
    public async Task DoesNotFireOnTheSynchronousFastPath(string statements)
    {
        Assert.Empty(await RunStatementsAsync(statements));
    }

    [Fact]
    public async Task DoesNotFireOnThingsThatOnlyLookLikeTasks()
    {
        var hits = await RunAsync("""
            using System.Runtime.CompilerServices;
            using System.Threading;
            using System.Threading.Tasks;

            namespace Shop;

            public sealed class Outcome
            {
                public int Result { get; init; }
                public void Wait() { }
            }

            public class Orders
            {
                public int Run(Outcome outcome, SemaphoreSlim gate, ManualResetEventSlim signal, object monitor)
                {
                    gate.Wait();
                    signal.Wait();
                    Monitor.Wait(monitor);
                    outcome.Wait();
                    Task.Yield().GetAwaiter().GetResult();
                    return outcome.Result;
                }
            }
            """);

        Assert.Empty(hits);
    }

    [Fact]
    public async Task DoesNotFireInsideNameof()
    {
        Assert.Empty(await RunStatementsAsync("var name = nameof(Task<int>.Result);"));
    }

    [Fact]
    public async Task DoesNotFireInAConfiguredMigrationExemptFolder()
    {
        const string source = """
            using System.Threading.Tasks;

            namespace Shop;

            public class Orders
            {
                public int Count(Task<int> pending) => pending.Result;
            }
            """;
        var configuration = new Dictionary<string, string>
        {
            [PortcullisConventionKeys.MigrationExemptFolders] = "Tests",
        };

        var diagnostics = await AnalyzerTestHelper.GetDiagnosticsAsync(
            new SyncOverAsyncAnalyzer(), configuration,
            ("src/Tests/Orders.cs", source), ("src/Shop/Orders.cs", source));

        var hit = Assert.Single(diagnostics, d => d.Id == RuleId);
        Assert.Equal("src/Shop/Orders.cs", hit.Location.SourceTree!.FilePath);
    }
}
